### ISSUE TITLE
Deprecated Building Method in 2019.3+

### ISSUE THREAD

**Issue by daltonbr** [mobfishgmbh/Cardboard-VR-Unity-SDK#51]
At **line 33** in `Cardboard/Editor/CardboardEditorHelper.cs`

```csharp
string target = proj.TargetGuidByName("Unity-iPhone");
```

Got this error 

> Error building Player: Exception: Calling TargetGuidByName with name='Unity-iPhone' is deprecated. There are two targets now, call [GetUnityMainTargetGuid()](https://docs.unity3d.com/ScriptReference/iOS.Xcode.PBXProject.GetUnityMainTargetGuid.html) - for app or [GetUnityFrameworkTargetGuid()](https://docs.unity3d.com/ScriptReference/iOS.Xcode.PBXProject.GetUnityFrameworkTargetGuid.html) - for source/plugins to get Guid instead.

My trivial solution was this.
```csharp
#if UNITY_2019_3_OR_NEWER
            string target = proj.GetUnityMainTargetGuid();
#else
            string target = proj.TargetGuidByName("Unity-iPhone");
#endif
```

**Comment by cai-mobfish** [comment]
Just going to create this issue and found this issue is already created.

2 points here:

- TargetGuidByName should not be used.
- Unity has now an extra targets, called UnityFramework, its bitcode has to be set to no in order to compile successfully. So multiple targets should be used to disable bitcode.

Fix is in testing and is on the way.

**Comment by daltonbr** [comment]
Very interesting, I was a bit confused by the documentation.
Great job @cai-mobfish! 👏

**Comment by cai-mobfish** [comment]
@daltonbr You can create a new ticket if documentation is not clear for you.
