### ISSUE TITLE
[Android] - Run VR scene error and crashed

### ISSUE THREAD

**Issue by imkrystal** [mobfishgmbh/Cardboard-VR-Unity-SDK#84]
Hi Team.

In iOS, it's seem OK, but in Android (Galaxy S9), when I run VR Scene it became error:

![Screenshot_20201109-131804_FOD_VR 1](https://user-images.githubusercontent.com/46667579/98506505-3e3fc880-228e-11eb-9ebc-cd3e6668eff8.jpg)

When I press QR code, app will be crashed. Here is my error log:

![image](https://user-images.githubusercontent.com/46667579/98506965-36ccef00-228f-11eb-8eb3-a55766033439.png)

Can you help me resolve this problem?

Thank you so much.

Best Regards!

**Comment by imkrystal** [comment]
Hi @cai-mobfish @cdytoby 
Can you help me resolve this problem?
Thank you so much.

**Comment by cdytoby** [comment]
Hello, sorry for the late response, it's been busy so I'm not able to respond to the tickets quickly.

To this question, it's because the protocol buffer for android implementation is not included.

You should create custom gradle file for android build, and include some android packages.

https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/wiki/Usage   
Detail can be found here, in the section "Additional Settings for Android"

**Comment by imkrystal** [comment]
Yeah. I check "https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK/wiki/Usage" and finally I fixed my problem.
Cause: I put everything your plugin folder in another folder and when I run VR mode, maybe it not file classes.
Now, I tested on GalaxyS9 and now it worked!!!
Maybe I will close this issue ;)
Thank you so much.
Best Regards!
